<?php

declare(strict_types=1);

namespace Neos\ContentGraph\DoctrineDbalAdapterForwardCompatibility\Schema\Command;

use Neos\ContentRepository\Core\SharedModel\ContentRepository\ContentRepositoryId;

class RenameContentGraphTablesMigrationBuilder
{
    public function __construct(
        public string $migrationVersion,
        public ContentRepositoryId $contentRepositoryId,
    ) {
    }

    public function build(): string
    {
        $cr = $this->contentRepositoryId->value;

        return <<<PHP
        <?php
        
        declare(strict_types=1);
        
        namespace Neos\Flow\Persistence\Doctrine\Migrations;
        
        use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;
        use Doctrine\DBAL\Schema\Schema;
        use Doctrine\Migrations\AbstractMigration;
        
        /**
         * Autogenerated migration to upgrade the content repository "{$cr}" to Neos 9.2
         * 
         * Copies the pre-patched Neos 9.2 content graph tables as the new current
         * 
         * See "./flow crprepatch:generatemigration" to build file for a given content repository
         * See all upgrade steps {@link https://github.com/neos/contentgraph-doctrinedbaladapter-forward-compatibility/pull/2}
         */
        final class Version{$this->migrationVersion} extends AbstractMigration
        {
            public function getDescription(): string
            {
                return 'Copies the pre-patched Neos 9.2 content graph tables as the new current for content repository "{$cr}". See docs https://github.com/neos/contentgraph-doctrinedbaladapter-forward-compatibility/pull/2';
            }
        
            public function up(Schema \$schema): void
            {
                \$this->abortIf(
                    !\$this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform,
                    "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\AbstractMySQLPlatform'."
                );
        
                // This migration was auto-generated by Neso, please do not edit. The database tables of the CR are not API
                // never manually modify the cr tables!
                // These sql statements are safe see documentation https://github.com/neos/contentgraph-doctrinedbaladapter-forward-compatibility/pull/2
                if (\$schema->hasTable('cr_{$cr}_p_92_graph_node')) {
                    \$this->addSql(<<<SQL
                    RENAME TABLE
                      # backup current tables as (cr_{$cr}_p_90_...)
                      cr_{$cr}_p_graph_contentstream TO cr_{$cr}_p_90_graph_contentstream,
                      cr_{$cr}_p_graph_dimensionspacepoints TO cr_{$cr}_p_90_graph_dimensionspacepoints,
                      cr_{$cr}_p_graph_hierarchyrelation TO cr_{$cr}_p_90_graph_hierarchyrelation,
                      cr_{$cr}_p_graph_node TO cr_{$cr}_p_90_graph_node,
                      cr_{$cr}_p_graph_referencerelation TO cr_{$cr}_p_90_graph_referencerelation,
                      cr_{$cr}_p_graph_workspace TO cr_{$cr}_p_90_graph_workspace,
                    
                      # rename new tables to current (cr_{$cr}_p_...)
                      cr_{$cr}_p_92_graph_contentstream TO cr_{$cr}_p_graph_contentstream,
                      cr_{$cr}_p_92_graph_contentstreamlayer TO cr_{$cr}_p_graph_contentstreamlayer,
                      cr_{$cr}_p_92_graph_dimensionspacepoints TO cr_{$cr}_p_graph_dimensionspacepoints,
                      cr_{$cr}_p_92_graph_hierarchyrelation TO cr_{$cr}_p_graph_hierarchyrelation,
                      cr_{$cr}_p_92_graph_node TO cr_{$cr}_p_graph_node,
                      cr_{$cr}_p_92_graph_referencerelation TO cr_{$cr}_p_graph_referencerelation,
                      cr_{$cr}_p_92_graph_workspace TO cr_{$cr}_p_graph_workspace
                    SQL);
                    
                    \$this->addSql(<<<SQL
                    # copy current state to new DETACHED subscription "contentGraph_90" and set new current
                    UPDATE cr_{$cr}_subscriptions
                      SET id = CASE id
                          WHEN 'contentGraph_92' THEN 'contentGraph'
                          WHEN 'contentGraph' THEN 'contentGraph_90'
                        END
                      WHERE id = 'contentGraph' OR id = 'contentGraph_92'
                    SQL);
                }
            }
        
            public function down(Schema \$schema): void
            {
                \$this->abortIf(
                    !\$this->connection->getDatabasePlatform() instanceof AbstractMySQLPlatform,
                    "Migration can only be executed safely on '\Doctrine\DBAL\Platforms\AbstractMySQLPlatform'."
                );
        
                if (\$schema->hasTable('cr_{$cr}_p_90_graph_node')) {
                    \$this->addSql(<<<SQL
                    RENAME TABLE
                      # restore current tables as (cr_{$cr}_p_92...)
                      cr_{$cr}_p_graph_contentstream TO cr_{$cr}_p_92_graph_contentstream,
                      cr_{$cr}_p_graph_contentstreamlayer TO cr_{$cr}_p_92_graph_contentstreamlayer,
                      cr_{$cr}_p_graph_dimensionspacepoints TO cr_{$cr}_p_92_graph_dimensionspacepoints,
                      cr_{$cr}_p_graph_hierarchyrelation TO cr_{$cr}_p_92_graph_hierarchyrelation,
                      cr_{$cr}_p_graph_node TO cr_{$cr}_p_92_graph_node,
                      cr_{$cr}_p_graph_referencerelation TO cr_{$cr}_p_92_graph_referencerelation,
                      cr_{$cr}_p_graph_workspace TO cr_{$cr}_p_92_graph_workspace,
                           
                      # restore original 90 current tables (cr_{$cr}_p_...)
                      cr_{$cr}_p_90_graph_contentstream TO cr_{$cr}_p_graph_contentstream,
                      cr_{$cr}_p_90_graph_dimensionspacepoints TO cr_{$cr}_p_graph_dimensionspacepoints,
                      cr_{$cr}_p_90_graph_hierarchyrelation TO cr_{$cr}_p_graph_hierarchyrelation,
                      cr_{$cr}_p_90_graph_node TO cr_{$cr}_p_graph_node,
                      cr_{$cr}_p_90_graph_referencerelation TO cr_{$cr}_p_graph_referencerelation,
                      cr_{$cr}_p_90_graph_workspace TO cr_{$cr}_p_graph_workspace
                    SQL);
                    
                    \$this->addSql(<<<SQL
                    # restore backup'd subscription to current
                    UPDATE cr_{$cr}_subscriptions
                      SET id = CASE id
                          WHEN 'contentGraph_90' THEN 'contentGraph'
                          WHEN 'contentGraph' THEN 'contentGraph_92'
                        END
                      WHERE id = 'contentGraph' OR id = 'contentGraph_90'
                    SQL);
                }
            }
        }
        PHP;
    }
}
