Neos:
  Flow:
    object:
      includeClasses:
        # disable proxies for generated code
        "Neos.ContentGraph.DoctrineDbalAdapterForwardCompatibility":
          - "Neos\\\\ContentGraph\\\\DoctrineDbalAdapterForwardCompatibility(?!\\\\Generated\\\\)"
