Neos:
  ContentRepositoryRegistry:
    presets:
      default:
        projections:
          "contentGraph_92":
            factoryObjectName: Neos\ContentGraph\DoctrineDbalAdapterForwardCompatibility\NextDoctrineDbalContentGraphProjectionFactory
