name: Tests

on:
  push:
    branches: [ '[0-9]+.[0-9]' ]
  pull_request:
    branches: [ '[0-9]+.[0-9]' ]
  workflow_dispatch: # Allow manual triggering on any branch via `gh workflow run tests.yml -r branch-name`

jobs:
  build:
    name: "Tests Neos ${{ matrix.neos-version }} (PHP ${{ matrix.php-version }}, ${{ matrix.db.image }})"
    env:
      FLOW_CONTEXT: Testing
      FLOW_PATH_ROOT: ../neos-base-distribution

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: "8.2"
            neos-version: "9.0"
            # comment in this line to use a specific branch of the neos dev collection
            # neos-dev-collection-branch: "task/..."
            db: { engine: mysql, image: 'mariadb:10.8', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' }

          - php-version: "8.3"
            neos-version: "9.0"
            # comment in this line to use a specific branch of the neos dev collection
            # neos-dev-collection-branch: "task/..."
            db: { engine: mysql, image: 'mariadb:10.8', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' }

          - php-version: "8.4"
            neos-version: "9.0"
            # comment in this line to use a specific branch of the neos dev collection
            # neos-dev-collection-branch: "task/..."
            db: { engine: mysql, image: 'mariadb:10.8', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' }

          - php-version: "8.4"
            neos-version: "9.1"
            # comment in this line to use a specific branch of the neos dev collection
            # neos-dev-collection-branch: "task/..."
            db: { engine: mysql, image: 'mariadb:10.8', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' }

          - php-version: "8.4"
            neos-version: "9.1"
            # comment in this line to use a specific branch of the neos dev collection
            # neos-dev-collection-branch: "task/..."
            db: { engine: mysql, image: 'mysql:8.0', port: 3306, options: '--health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3' }

    services:
      database:
        image: ${{ matrix.db.image }}
        env:
          MYSQL_USER: neos
          MYSQL_PASSWORD: neos
          MYSQL_DATABASE: neos_behaviour_testing
          MYSQL_ROOT_PASSWORD: neos
        ports:
          - "${{ matrix.db.port }}:${{ matrix.db.port }}"
        options: ${{ matrix.db.options }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite, mysql

      - id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Prepare Neos distribution
        run: |
          git clone --depth 1 --branch 9.2 https://github.com/neos/neos-development-collection.git ../Neos_92_Sources

          git clone --depth 1 --branch ${{ matrix.neos-version }} https://github.com/neos/neos-development-distribution.git ${FLOW_PATH_ROOT}
          cd ${FLOW_PATH_ROOT}
          
          ${{ matrix.neos-dev-collection-branch &&
              format('composer require --no-update --no-interaction "neos/neos-development-collection:dev-{0} as {1}.x-dev"', matrix.neos-dev-collection-branch, matrix.neos-version)
          }}

          composer config --no-plugins allow-plugins.neos/composer-plugin true
          
          composer config repositories.package '{ "type": "path", "url": "../contentgraph-doctrinedbaladapter-forward-compatibility", "options": { "symlink": false } }'
          composer require --no-update --no-interaction neos/contentgraph-doctrinedbaladapter-forward-compatibility:@dev
          
          composer require --dev --no-update --no-interaction phpstan/phpstan:^1.10

      - name: Install dependencies
        run: |
          cd ${FLOW_PATH_ROOT}
          composer install --no-interaction --no-progress --prefer-dist

      - name: Linting
        run: |
          cd ${FLOW_PATH_ROOT}/Packages/Application/Neos.ContentGraph.DoctrineDbalAdapterForwardCompatibility
          composer run lint:phpstan

      # - name: Run Unit tests
      #   run: |
      #     cd ${FLOW_PATH_ROOT}
      #     bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Neos.ContentGraph.DoctrineDbalAdapterForwardCompatibility/Tests/Unit

      - name: Setup Flow configuration
        run: |
          cd ${FLOW_PATH_ROOT}
          rm -f Configuration/Testing/Settings.yaml
          
          cat <<EOF >> Configuration/Testing/Settings.yaml
          Neos:
            Flow:
              persistence:
                backendOptions:
                  host: '127.0.0.1'
                  port: ${{ matrix.db.port }}
                  driver: pdo_mysql
                  user: 'neos'
                  password: 'neos'
                  dbname: 'neos_behaviour_testing'
          EOF

          # Configure new graph projection

          mkdir Configuration/Testing/Behat

          cat <<EOF >> Configuration/Testing/Behat/Settings.ContentRepositoryRegistry.yaml
          Neos:
            ContentRepositoryRegistry:
              presets:
                default:
                  contentGraphProjection:
                    factoryObjectName: Neos\ContentGraph\DoctrineDbalAdapterForwardCompatibility\Testing\TestingNextDoctrineDbalContentGraphProjectionFactory
                  projections:
                    contentGraph_92: ~
          EOF

          cat <<EOF >> Configuration/Testing/Behat/Objects.yaml
          Neos\ContentRepository\Core\Projection\ContentGraph\ProjectionIntegrityViolationDetectionRunnerFactoryInterface:
            scope: singleton
            factoryObjectName: 'Neos\ContentRepositoryRegistry\Infrastructure\GenericObjectFactory'
            arguments:
              1:
                value: 'Neos\ContentGraph\DoctrineDbalAdapterForwardCompatibility\Generated\ContentGraph\DoctrineDbalProjectionIntegrityViolationDetectionRunnerFactory'
              2:
                object: 'Doctrine\DBAL\Connection'

          EOF

      - name: Run Functional tests
        run: |
          cd ${FLOW_PATH_ROOT}
          bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Neos.ContentGraph.DoctrineDbalAdapterForwardCompatibility/Tests/Functional

      - name: Run doctrine migrate
        # prevent db transaction in connection from being closed by migrating in advance
        run: |
          cd ${FLOW_PATH_ROOT}
          FLOW_CONTEXT=Testing/Behat ./flow doctrine:migrate --quiet

      - name: Run behat Neos.ContentRepository.BehavioralTests tests with new graph projection
        run: |
          cd ${FLOW_PATH_ROOT}
          FLOW_CONTEXT=Testing/Behat ./flow testingcontentgraphprojection:validatecontentrepository default
          FLOW_CONTEXT=Testing/Behat bin/behat -f progress --strict --no-interaction -c Packages/Neos/Neos.ContentRepository.BehavioralTests/Tests/Behavior/behat.yml.dist ../Neos_92_Sources/Neos.ContentRepository.BehavioralTests/Tests/Behavior/Features -vvv --stop-on-failure

      - name: Show log on failure
        if: ${{ failure()  }}
        shell: bash
        run: |
          cd ${FLOW_PATH_ROOT}
          # cat Data/Logs/System_Testing.log
          if compgen -G "Data/Logs/Exceptions/*" > /dev/null; then
            for file in Data/Logs/Exceptions/*; do
              echo $file
              cat $file
            done
          fi
